### ISSUE TITLE
Are binaries built for Android expected to work?

### ISSUE THREAD

**Issue by crujose** [google/bloaty#81] opened 2017-11-10 02:33 UTC
Basic things seem to work but I'm running into odd things like this:

```
$ bloaty libsample.so -d inlines
bloaty: premature EOF skipping DWARF data
```

Any ideas?

**Comment by haberman** [comment] 2017-11-11 16:58
Yep, it should work! I would guess it is likely a bug from running on a 32-bit architecture. I will try to test on x86 (32 bit) soon to see if I can reproduce the bug.

**Comment by crujose** [comment] 2017-11-13 18:04
If things are sensitive to the runtime environment I guess it would help to clarify that I'm running this on MacOS 10.12 (64bit).

Also, here's the output from `file`
`libsample.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, with debug_info, not stripped`

**Comment by DanAlbert** [comment] 2017-11-17 19:42
I see the same thing when trying to analyze arm32 Android stuff from Linux x86_64. It works if I back all the way up to 73594cde8c9a52a102c4341c244c833aa61b9c06 (not bisected, it's just the version I'd originally checked out).

**Comment by haberman** [comment] 2017-11-17 20:09
Hmm, could you possibly upload such a file or send me a repro for how to build binaries in this way?

**Comment by DanAlbert** [comment] 2017-11-17 20:22
I've narrowed it down to #63. If I checkout to https://github.com/google/bloaty/commit/b68d009fedca873b79d8fdf24cba8a8f3c44a1f3, it works, but it breaks at https://github.com/google/bloaty/commit/a7fa43b7fb7192d12cefa7e7669c606f67a6bf10.

Here's a test file: [gcc.so.txt](https://github.com/google/bloaty/files/1483704/gcc.so.txt). It's a .txt extension because github wouldn't let me upload a .so. Just rename it. Interestingly I don't see this problem if I build the same library with Clang.

I can upload a test case that you can build if that helps, but you'd have to download the NDK to build it (and I'd need to do a bit more minimizing).

**Comment by DanAlbert** [comment] 2017-11-17 20:33
Reverting each patch in #63 one at a time shows that it was caused by https://github.com/google/bloaty/pull/63/commits/5b19685d6c2bd4bbdc16927571d013f861b1b099. That patch definitely added that error message. Prior to that it was a `CHECK_RETURN` though. Was the return value being ignored, maybe?

**Comment by haberman** [comment] 2017-11-22 00:53
This was a bug, fixed in https://github.com/google/bloaty/commit/f89fb55ea5560160a12592e909cb8ab08a1cfb51.

**Closed by haberman** 2017-11-22 00:53 UTC
