### ISSUE TITLE
Compile fails due to undefined `UINT64_MAX`

### ISSUE THREAD

**Issue by jchl** [google/bloaty#26] opened 2016-11-14 17:46 UTC
On my system (Linux/x86_84 and gcc 4.7.2), make fails with:

```
src/bloaty.h: In member function ‘bool bloaty::RangeMap::Entry::HasTranslation() const’:
src/bloaty.h:294:57: error: ‘UINT64_MAX’ was not declared in this scope
```

Adding `#define __STDC_LIMIT_MACROS` before the `#include <stdint.h>` in bloaty.h fixes the problem.

**Comment by haberman** [comment] 2016-11-14 17:48
Sounds good, want to send a pull request? It seems better to get the fix from you since I can't reproduce the compile failure on my own machine.

**Comment by haberman** [comment] 2016-11-14 23:46
Should be fixed due to merging of https://github.com/google/bloaty/pull/29

**Closed** 2016-11-14 23:46 UTC
